### ISSUE TITLE
error when run the workflow, and the list in past runs all failed, 

### ISSUE THREAD

**Issue by HsiaoJuhn** [nathannlu/ComfyUI-Cloud#11]
**Describe the bu

**To Reproduce**

![Sp_2024-03-26_11-16-20](https://github.com/nathannlu/ComfyUI-Cloud/assets/156157237/59a955be-bc03-4f40-9450-82c8a9c696fa)

**Comment by nathannlu** [comment]
Hi was this during the first time you upload your workflow? If so, it is a bug I'm currently working on fixing. Seems to be affecting users who are using multiple models in their workflow, let me know if that is your case!

**Comment by HsiaoJuhn** [comment]
Hi, yes, it's the first time, and I only use the default workflow.

**Comment by nathannlu** [comment]
Hmm this shouldn't be happening if it is the default case, can you join the Discord and shoot me a DM? I will take a deeper look!

**Comment by nathannlu** [comment]
Hi I pushed a patch that fixes this. Let me know if you are still having issues!
