### ISSUE TITLE
Error: Cannot connect to host

### ISSUE THREAD

**Issue by BayJ233** [nathannlu/ComfyUI-Cloud#12]
Error: Cannot connect to host pytest-12acbe397fbc.herokuapp.com:443 ssl:default [Connect call failed ('66.220.149.32', 443)]
Is this a network problem?

**Comment by nathannlu** [comment]
hi let me take look at this and get back to you asap

**Comment by nathannlu** [comment]
hi @BayJ233 can you provide more details on the steps leading up to this issue? Also if you could dm on Discord I can help you get everything set up!

**Comment by BayJ233** [comment]
可以给我一个discord频道地址吗

**Comment by BayJ233** [comment]
Can you give me a discord channel address?

**Comment by nathannlu** [comment]
For sure! https://discord.gg/2PTNx3VCYa
