### ISSUE TITLE
Where is the website

### ISSUE THREAD

**Issue by softyoda** [nathannlu/ComfyUI-Cloud#15]
Where to register, how does this work ? Is it maintained ? How much does it cost ? Do you only pay inference, or you pay for hour of usage (even in idle) ?

**Comment by nathannlu** [comment]
Hi! You can find all the info in our docs :) 
https://github.com/nathannlu/ComfyUI-Cloud/blob/main/docs/get-started.md

**Comment by softyoda** [comment]
FYI for others reading this issue, there are no website.

![image](https://github.com/nathannlu/ComfyUI-Cloud/assets/13988751/8f92370c-c89f-4031-aa7b-98374c27a94f)
