### ISSUE TITLE
IMPORT FAILED (M1 MACBOOK AIR)

### ISSUE THREAD

**Issue by sakdon** [nathannlu/comfyui-cloud#2]
After installing cloud git on the vanilla version, it seems like there's a "lack of NODE..." issue preventing loading. Also, after getting permissions from the login site and hitting close, I encounter a "TypeError: Failed to fetch" error. I really think this solution has potential. Is there any way to fix these issues?

--- log ---

### ComfyUI Revision: 1985 [929e266f] | Released on '2024-02-17'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
Skip /Users/sakdon/Documents/Stable_Diffusion/ComfyUI/ComfyUI/custom_nodes/comfyui-cloud module for custom nodes due to the lack of NODE_CLASS_MAPPINGS.

Import times for custom nodes:
   0.1 seconds: /Users/sakdon/Documents/Stable_Diffusion/ComfyUI/ComfyUI/custom_nodes/ComfyUI-Manager
   0.2 seconds (IMPORT FAILED): /Users/sakdon/Documents/Stable_Diffusion/ComfyUI/ComfyUI/custom_nodes/comfyui-cloud

Starting server

**Comment by nathannlu** [comment]
Thanks for bringing this to my attention. Gonna take a look today

**Comment by nathannlu** [comment]
Hi this issue has been fixed. Please let me know if you are still experiencing issues.

PR: https://github.com/nathannlu/comfyui-cloud/pull/3

**Comment by sakdon** [comment]
> Hi this issue has been fixed. Please let me know if you are still experiencing issues.
> 
> PR: #3

Oh it works now! Thanks for the fix! :)
