### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by ryo0ka** [nathannlu/ComfyUI-Cloud#32]
**Describe the bug**
Modal shows `Error: Failed to upload` upon uploading a workflow containing multiple large files, as in attached image below.

API response corresponding to the error contains the following text:
```html
<html>
  <head><title>413 Request Entity Too Large</title></head>
  <body>
    <center><h1>413 Request Entity Too Large</h1></center>
    <hr><center>nginx/1.24.0 (Ubuntu)</center>
  </body>
</html>
```

Error log as following:
```
Upload task execution error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://storage.comfyui-cloud.com/upload-urls')
```

**To Reproduce**
1. Load [workflow.json](https://github.com/user-attachments/files/16424028/workflow.json);
2. Download assets from [tutorial](https://civitai.com/articles/2379) and set up inputs;
3. Tap `Generate on cloud GPU` button;
4. Wait for uploads to complete;
5. See the modal pop up.

**Expected behavior**
Workflow should be accepted.

**Screenshots**
![image](https://github.com/user-attachments/assets/50701a24-b171-4980-af33-d4f65c90eaf3)

**Desktop:**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 126.0.6478.185

**Additional context**
The workflow is part of a popular tutorial on video-to-video workflows using Animatediff. Since vid2vid requires large VRAM, I expect that many users would opt out to cloud-based solutions like Comfy Cloud.

**Comment by nathannlu** [comment]
hi @ryo0ka , just pushed a fix for this. thank you for providing the details. let me know if your issue has been resolved!

**Comment by ryo0ka** [comment]
@nathannlu Got it working, thanks a bunch. Got another issue related to ControlNet which I will dig in and let you know if it may be on your side, cheers
