### ISSUE TITLE
[Request] Adding general information and pricing about Cloud service inside README

### ISSUE THREAD

**Issue by LukeG89** [nathannlu/ComfyUI-Cloud#5]
Hi @nathannlu, thank you for creating this custom node!

I see that there is no information about Cloud service, such as **pricing**, **privacy** and **security**.

For example:
- How much does it cost?
- What GPUs are used?
- Where the generated images/videos will be stored? For how long?
- Are my content private?

Sorry for all these questions, but I would like to know everything before using it.

Could you please provide all these information inside README file? It would be helpful for all users!

Thanks a lot!

**Comment by nathannlu** [comment]
Thank you for the questions @LukeG89. Sorry for the delayed response, I respond faster on Discord!

We are still working out the pricing at the moment but the current cost is $0.0006/s of image generation time (this means you only pay for the time when your workflow is executing, not when you are building the workflow).

GPU used is Nvidia A10G, 24GB, and generated images/videos are stored until you delete the workflow in the https://comfycloud.vercel.app/ dashboard.

Yes your content is private. We encrypt your generated images using Advanced Encryption Standard (AES). However, your custom nodes and models that are uploaded to the cloud before we execute your workflow is not encrypted, but also not public.

I appreciate you asking the questions -- as you can see with the README, I'm not sure what information users would like to see... Would love to chat with you more! If you are open to it shoot me a message on Discord :)

**Comment by RyzeNGrind** [comment]
Hi @nathannlu how can I use this tool to connect to my own hybrid cloud of GPUs in my homelab? Is there any provider options for adding self hosted cloud providers or choosing alternative cloud providers?

**Comment by nathannlu** [comment]
> Hi @nathannlu how can I use this tool to connect to my own hybrid cloud of GPUs in my homelab? Is there any provider options for adding self hosted cloud providers or choosing alternative cloud providers?

Hi! We don't support connecting to local GPUs or other providers unfortunately. This custom node works as a out of the box solution. Feel free to shoot me a dm on Discord maybe I can help you out!
