### ISSUE TITLE
 Executing ... Syncing run but nothing append

### ISSUE THREAD

**Issue by mikecastrodemaria** [nathannlu/ComfyUI-Cloud#6]
**Describe the bug**
I hit "generate on cloud GPU" , the message tell me  Executing under Syncing animation, but nothing append.
I well set my account, I create the wokflow name I can see on the website, after I created.

**To Reproduce**
1. Click on "generate on cloud GPU" button
2. See Syncing message
3. See nothing append

**Screenshots**
<img width="687" alt="Capture d’écran 2024-03-10 à 21 42 25" src="https://github.com/nathannlu/ComfyUI-Cloud/assets/295538/6dacc4cc-5993-4a8c-a14d-22b17a0dc08b">

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.4 (23E214)
 - Browser : chrome Version 121.0.6167.85 (Official Build) (arm64)

** ComfyUI startup time: 2024-03-10 21:43:53.560364
** Platform: Darwin
** Python version: 3.10.6 (v3.10.6:9c7b4bd164, Aug  1 2022, 17:13:48) [Clang 13.0.0 (clang-1300.0.29.30)]
** Python executable: /Volumes/..../ComfyUI/venv/bin/python
** Log path: /Volumes/..../ComfyUI/comfyui.log
** Comfy Cloud Revision: 349f67b6c779cb49b41598c2f72d7bd9083f1f41

I can provide what you need, just ask.

Thanks

**Comment by nathannlu** [comment]
Hi! Can you please dm me the Comfy Cloud logs on Discord? I can take a look! The log files are inside /custom_nodes/ComfyUI-Cloud/logs folder.
